# Quarkus usa Jandex para indexar @Provider, @ApplicationScoped, etc.
# Por defecto solo indexa las clases del proyecto actual. Para que el
# `ApiExceptionMapper` de `nova-api-standard-quarkus-extension` sea descubierto, declaramos
# la dependencia como indexable.
quarkus.index-dependency.nova-api-standard-quarkus-extension.group-id=pe.edu.nova.java.starters
quarkus.index-dependency.nova-api-standard-quarkus-extension.artifact-id=nova-api-standard-quarkus-extension
