# Quarkus usa Jandex para indexar @Provider, @ApplicationScoped, etc.
# Por defecto solo indexa las clases del proyecto actual. Para que el
# `ApiExceptionMapper` de `nova-quarkus-api-ext` sea descubierto, declaramos
# la dependencia como indexable.
quarkus.index-dependency.nova-quarkus-api-ext.group-id=pe.edu.nova.java.starters
quarkus.index-dependency.nova-quarkus-api-ext.artifact-id=nova-quarkus-api-ext
